version: '3'

services:
  database:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
  database_test:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ~/postgres_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db_test
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      - database
      - database_test
    ports:
      - "8888:80"
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: user@database.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ~/pgadmin-data:/var/lib/pgadmin

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
      - database_test
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www

volumes:
  local_pgdata:
  pgadmin-data: