version: '3'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
